server.port=8080

spring.application.name=transfer
spring.datasource.url=jdbc:h2:mem:transferdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.mode=always

spring.data.redis.host=localhost
spring.data.redis.port=6379

aws.endpoint-url=http://localhost:4566
aws.region=us-east-1
aws.access-key=test
aws.secret-key=test
aws.sqs.queue-url=http://localhost:4566/000000000000/bacen-events
aws.sqs.dlq-url=http://localhost:4566/000000000000/bacen-events-dlq

cadastro.api.url=http://localhost:8081
bacen.api.url=http://localhost:8082

resilience4j.circuitbreaker.instances.cadastro.register-health-indicator=true
resilience4j.circuitbreaker.instances.cadastro.sliding-window-size=10
resilience4j.circuitbreaker.instances.cadastro.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.cadastro.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.cadastro.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.cadastro.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.cadastro.ignore-exceptions=feign.FeignException.FeignClientException

resilience4j.retry.instances.cadastro.max-attempts=3
resilience4j.retry.instances.cadastro.wait-duration=500ms
resilience4j.retry.instances.cadastro.enable-exponential-backoff=true
resilience4j.retry.instances.cadastro.exponential-backoff-multiplier=2

resilience4j.retry.instances.bacen.max-attempts=3
resilience4j.retry.instances.bacen.wait-duration=1s
resilience4j.retry.instances.bacen.enable-exponential-backoff=true
resilience4j.retry.instances.bacen.exponential-backoff-multiplier=2
resilience4j.retry.instances.bacen.ignore-exceptions=com.personal.transfer.infrastructure.adapters.BacenRateLimitException

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0

transfer.daily-limit=1000.00

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [traceId=%X{traceId},spanId=%X{spanId}] %logger{36} - %msg%n
